### ISSUE TITLE
Unable to add to list

### ISSUE THREAD

**Issue by hjpotter92** [dedi/gxref#9]
I have gxref installed, however, when I put the following

```elisp
    (add-to-list 'xref-backend-functions 'gxref-xref-backend)
```
in my `init.el`, I get:

```
Symbol’s value as variable is void: xref-backend-functions
```

**Comment by aaptel** [comment]
You need a recent emacs (>25.1) and you need to have xref loaded before running it

    (require 'xref)
    (require 'gxref)
    (add-to-list 'xref-backend-functions 'gxref-xref-backend)

**Comment by hjpotter92** [comment]
@aaptel Yes. I was trying in emacs 24. Compiled and installed 26.1 now, and gxref is working :)

Thanks
